spring:
  profiles:
    active: docker,dev
  application:
    name: auth-service
  config:
    import: optional:configserver:${CONFIG_SERVER_URL:http://localhost:8888/}
logging:
  level:
    org.springframework.cloud: DEBUG